# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- tagcloud
- category
#- tag
- archive
- blogroll

# Miscellaneous
# google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
baidu_tongji:

# image URL
qiniu_url: http://7xnlhz.com1.z0.glb.clouddn.com
